# Generated by Django 5.2 on 2025-04-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metricas", "0002_userprofile_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
